name: Checks if the current version's tag has been released

on:
  workflow_call:
    outputs:
      version:
        description: 'The version number of the release'
        value: ${{ jobs.check_version.outputs.version }}
      should_run:
        description: 'Whether other jobs should run or not (false or empty)'
        value: ${{ jobs.check_version.outputs.should_run }}

jobs:
  check_version:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      version: ${{ steps.check_version.outputs.version }}
      should_run: ${{ steps.check_version.outputs.should_run }}
    steps:
      - id: check_version
        continue-on-error: true
        name: check latest commit is less than a day
        run: |
          git clone --depth=1 https://${{ github.token }}@github.com/${{ github.repository }} e-l
          cd e-l
          VERSION="$(cat src/electron/ELECTRON_VERSION)"
          echo "::set-output name=version::$VERSION"
          git ls-remote --tags --exit-code -q https://github.com/${{ github.repository }} "refs/tags/$VERSION" && echo "::set-output name=should_run::false"
