name: Generate SHA
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:
  generate_sha:
    runs-on: ubuntu-latest
    name: Generate SHASUMS256.txt
    steps:
      - uses: actions/checkout@v3
      - name: View context attributes
        uses: actions/github-script@v6
        env:
          VERSION: ${{ inputs.version }}
        with:
          script: |
            const script = require('./ci/script.js')
            await script({github})
      - name: Upload SHASUM256.txt
        uses: actions/upload-artifact@v3
        with:
          name: shasum-${{inputs.version}}
          path: ./ci/SHASUMS256.txt
