name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'v20.3.0-rc'
      build_macos:
        description: 'Build macOS'
        required: false
        type: boolean

jobs:
  build_release_mac:
    name: Build for Mac ${{ matrix.name }}
    if: ${{ github.event.inputs.build_macos }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: arm64
            runner: macro-arm1
    uses: ./.github/workflows/build_mac.yml
    with:
      version: ${{ github.event.inputs.version }}
      runner_label: ${{ matrix.runner }}
  generate_sha:
    name: Generate SHA
    needs: [build_release_mac]
    uses: ./.github/workflows/generate-sha.yml
    with:
      version: ${{ github.event.inputs.version }}
  publish:
    name: Publish Electron to NPM Registry
    needs: [generate_sha]
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets:
      NPM_AUTH: ${{ secrets.NPM_AUTH }}
