name: Publish
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      NPM_AUTH:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Update electron package
        uses: actions/github-script@v6
        env:
          VERSION: ${{ inputs.version }}
        with:
          script: |
            const script = require('./ci/updatePackageForRelease.js')
            await script({github})
      - name: Attach License
        run: |
          cp ./LICENSE ./src/electron/npm
      - name: Copy LOK TypeScript to NPM folder
        run: |
          export LC_ALL=en_US.utf8
          lok_version="$(cat src/electron/DEPS | grep -oP "'libreofficekit_version': '\\K[^']+")"
          rm -rf instdir || true
          rm -f libreofficekit-linux.tar.xz || true
          curl -LO "https://github.com/coparse-inc/libreofficekit/releases/download/$lok_version/libreofficekit-linux.tar.xz"
          tar -xJf libreofficekit-linux.tar.xz
          cp -rf instdir/sdk/typescript ./src/electron/npm/lok_api
      - name: Publish package on NPM
        run: |
          cd src/electron/npm
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH }}
